-- CREATE TABLE users (id NOT NULL PRIMARY KEY , username NOT NULL,password NOT NULL,email NOT NULL);
-- INSERT INTO users (id,username,password,email) VALUES ("1","nanduaru","nandu@7328","nanduaru333@gmail.com");
-- INSERT INTO movies (id,image_url,alt) VALUES ("2","https://res.cloudinary.com/duv0mhzrm/image/upload/v1665898963/cld-sample-4.jpg","sample");